# plugins:  
#     - jekyll-paginate
#     - jekyll-redirect-from

# Build settings

baseurl: /
url: https://trungthanhnguyen0502.github.io

markdown: kramdown
permalink: pretty
future: true
highlighter: rouge
linenos: true
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge